spring.application.name=ResumeIq

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# API Configuration
api.version=v1.0
api.base-path=/api
server.servlet.context-path=${api.base-path}/${api.version}

# Server Configuration
server.port=${PORT:8080}

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Gemini API
gemini.api.key=${GEMINI_API_KEY}